{{ containerfile }}

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx {{ bin_dir }}/
{% if npx -%}
COPY --from=oven/bun:latest /usr/local/bin/bun* {{ bin_dir }}/
{%- endif %}

{% if env_vars -%}
{% for key, value in env_vars.items() %}
ENV {{ key }}={{ value }}
{% endfor %}
{%- endif %}

RUN uvx acp-agent setup {{ agent_id }}

{% if workdir -%}
WORKDIR {{ workdir }}
{%- endif %}

CMD [{% for part in cmd %}"{{ part }}"{% if not loop.last %}, {% endif %}{% endfor %}]
