{% if binary.archive -%}
FROM docker.io/curlimages/curl:latest AS essentials
USER root
RUN curl -fSL "{{ binary.archive }}" -o "/bin/{{ binary.cmd }}" && chmod +x "/bin/{{ binary.cmd }}"
{%- endif %}

{{ containerfile }}

{% if binary.archive -%}
COPY --from=essentials /bin/{{ binary.cmd }} {{ bin_dir }}/{{ binary.cmd }}
{%- endif %}
{% if npx -%}
COPY --from=oven/bun:latest /usr/local/bin/bun* {{ bin_dir }}/
{%- endif %}
{% if uvx -%}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx {{ bin_dir }}/
{%- endif %}

{% if env_vars -%}
{% for key, value in env_vars.items() %}
ENV {{ key }}={{ value }}
{% endfor %}
{%- endif %}

{% if workdir -%}
WORKDIR {{ workdir }}
{%- endif %}

CMD [{% for part in cmd %}"{{ part }}"{% if not loop.last %}, {% endif %}{% endfor %}]
