{{ containerfile }}

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx {{ bin_dir }}/
RUN uvx acp-agent setup {{ agent_id }}

{% if npx -%}
COPY --from=oven/bun:latest /usr/local/bin/bun* {{ bin_dir }}/
{%- endif %}

{% if env_vars -%}
{% for key, value in env_vars.items() %}
ENV {{ key }}={{ value }}
{% endfor %}
{%- endif %}

{% if workdir -%}
WORKDIR {{ workdir }}
{%- endif %}

{% if mode == 'sleep' -%}
CMD ["sleep", "infinity"]
{% elif mode == 'run' -%}
CMD ["uvx", "acp-agent", "run", "{{ agent_id }}"]
{% endif %}
